const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const GET_NUMBER_OF_USERS_SUCCESS = "GET_NUMBER_OF_USERS_SUCCESS";
const GET_TOP_USERS_SUCCESS = "GET_TOP_USERS_SUCCESS";

const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
const GET_NUMBER_OF_POSTS_SUCCESS = "GET_NUMBER_OF_POSTS_SUCCESS";
const GET_TOP_POSTS_SUCCESS = "GET_TOP_POSTS_SUCCESS";
const INC_LIKE = "INC_LIKE";
const DEC_LIKE = "DEC_LIKE";

export {
  CREATE_USER_SUCCESS,
  GET_USERS_SUCCESS,
  DELETE_USER_SUCCESS,
  GET_SINGLE_USER_SUCCESS,
  UPDATE_USER_SUCCESS,
  GET_NUMBER_OF_USERS_SUCCESS,
  GET_TOP_USERS_SUCCESS,
  CREATE_POST_SUCCESS,
  DELETE_POST_SUCCESS,
  GET_SINGLE_POST_SUCCESS,
  GET_POSTS_SUCCESS,
  UPDATE_POST_SUCCESS,
  GET_NUMBER_OF_POSTS_SUCCESS,
  GET_TOP_POSTS_SUCCESS,
  INC_LIKE,
  DEC_LIKE,
};
